name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter-book ghp-import
        
    - name: Build Jupyter Book
      run: |
        jupyter-book build --all ./
        
    - name: Deploy to GitHub Pages
      run: |
        ghp-import -o -n -p -f _build/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jupyter-book-build
        path: _build/html/
